/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.UsuarioIncorrecto;
import concesionario.Administrador;
import concesionario.GestorUsuarios;
import concesionario.Usuario;
import concesionario.Utilidades;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



public class VentanaValidacionUsuario extends javax.swing.JDialog {

    private GestorUsuarios gestorUsuarios; 
    private JFrame parent;
    
    public VentanaValidacionUsuario(JFrame parent, boolean modal, String codigoUsuario) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
        this.codigoTF.setText(codigoUsuario);
        gestorUsuarios = GestorUsuarios.getInstance();
        
        nombreConcesionarioLB.setText(Utilidades.getNombreConcesionario());
        fechaLB.setText(Utilidades.getFechaHoy());
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreConcesionarioLB = new javax.swing.JLabel();
        fechaLB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        codigoTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        contrasenaPF = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        aceptarJB = new javax.swing.JButton();
        limpiarJB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        nombreConcesionarioLB.setText("Concesionario X");
        jPanel1.add(nombreConcesionarioLB);

        fechaLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fechaLB.setText("FECHA");
        jPanel1.add(fechaLB);

        getContentPane().add(jPanel1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INICIO DE SESION");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CODIGO DE USUARIO");
        jPanel3.add(jLabel4);
        jPanel3.add(codigoTF);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CONTRASEÑA");
        jPanel3.add(jLabel5);
        jPanel3.add(contrasenaPF);

        aceptarJB.setText("ACEPTAR");
        aceptarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarJBActionPerformed(evt);
            }
        });
        jPanel4.add(aceptarJB);

        limpiarJB.setText("LIMPIAR");
        limpiarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarJBActionPerformed(evt);
            }
        });
        jPanel4.add(limpiarJB);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarJBActionPerformed
        try { 

            String codigo = codigoTF.getText();
            String contrasena = new String(contrasenaPF.getPassword());

            if (gestorUsuarios.comprobarUsuario(codigo, contrasena)) {
                Usuario user = gestorUsuarios.obtenerUsuario(codigo); 
                this.setVisible(false);
                
                if (user instanceof Administrador) // todo aquel que sea administrador tendra activada opciones especiales
                    new VentanaPrincipal(parent, true, true, codigo);
                else 
                    new VentanaPrincipal(parent, true, false, codigo);
                

                this.setVisible(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Contraseña incorrecta.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (UsuarioIncorrecto e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarJBActionPerformed

    private void limpiarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarJBActionPerformed
// TODO add your handling code here:
        codigoTF.setText("");
        contrasenaPF.setText("");
    }//GEN-LAST:event_limpiarJBActionPerformed

  
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarJB;
    private javax.swing.JTextField codigoTF;
    private javax.swing.JPasswordField contrasenaPF;
    private javax.swing.JLabel fechaLB;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton limpiarJB;
    private javax.swing.JLabel nombreConcesionarioLB;
    // End of variables declaration//GEN-END:variables
}
