/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.MatriculaExistente;
import Excepciones.UsuarioIncorrecto;
import concesionario.Concesionario;
import concesionario.GestorUsuarios;
import concesionario.Usuario;
import concesionario.Utilidades;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class VentanaPrincipal extends javax.swing.JDialog {

    private GestorUsuarios gestorUsuarios;
    private Concesionario concesionario;
    private JFrame parent;
    private String codigoUsuario;
    
    public VentanaPrincipal(JFrame parent, boolean modal, boolean modoAdministrador, String codigoUsuario) {
        super(parent, modal);
        this.parent = parent;
        concesionario = Concesionario.getInstance();
        gestorUsuarios = GestorUsuarios.getInstance();
        try {
            concesionario.cargarConcesionario();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se a podido cargar los datos del concesionario.","fallo",JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se a podido cargar los datos del concesionario.","fallo",JOptionPane.ERROR_MESSAGE);
        }
        
        this.codigoUsuario = codigoUsuario;
        initComponents();
               
        alta_bajaMI.setVisible(modoAdministrador);
        nombreConcesionarioLB.setText(Utilidades.getNombreConcesionario());
        fechaLB.setText(Utilidades.getFechaHoy());
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        pieVentanaLB = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        nombreConcesionarioLB = new javax.swing.JLabel();
        fechaLB = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu15 = new javax.swing.JMenu();
        guardarDatosMI = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        nuevoVehiculoMI = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        nuevaReparacionMI = new javax.swing.JMenuItem();
        historialVehiculoMI = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        nuevaVentaMI = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        cambiarContrasenaMI = new javax.swing.JMenuItem();
        alta_bajaMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jLabel1.setText("Tu sesion se ha iniciado correctamente");
        jToolBar1.add(jLabel1);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(pieVentanaLB);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        nombreConcesionarioLB.setText("Concesionario X");
        jPanel1.add(nombreConcesionarioLB);

        fechaLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fechaLB.setText("FECHA");
        jPanel1.add(fechaLB);

        jMenu15.setText("Inicio");

        guardarDatosMI.setText("Guardar Datos");
        guardarDatosMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                guardarDatosMIMousePressed(evt);
            }
        });
        guardarDatosMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDatosMIActionPerformed(evt);
            }
        });
        jMenu15.add(guardarDatosMI);

        jMenuBar3.add(jMenu15);

        jMenu13.setText("Exposicion");

        nuevoVehiculoMI.setText("Admision de Vehiculo");
        nuevoVehiculoMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevoVehiculoMIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevoVehiculoMIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevoVehiculoMIMousePressed(evt);
            }
        });
        nuevoVehiculoMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoVehiculoMIActionPerformed(evt);
            }
        });
        jMenu13.add(nuevoVehiculoMI);

        jMenuBar3.add(jMenu13);

        jMenu11.setText("Reparaciones");
        jMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu11MouseExited(evt);
            }
        });

        nuevaReparacionMI.setText("Nueva Reparacion");
        nuevaReparacionMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevaReparacionMIMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nuevaReparacionMIMousePressed(evt);
            }
        });
        nuevaReparacionMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaReparacionMIActionPerformed(evt);
            }
        });
        jMenu11.add(nuevaReparacionMI);

        historialVehiculoMI.setText("Ver Historial de un vehiculo");
        historialVehiculoMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                historialVehiculoMIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                historialVehiculoMIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                historialVehiculoMIMousePressed(evt);
            }
        });
        historialVehiculoMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialVehiculoMIActionPerformed(evt);
            }
        });
        jMenu11.add(historialVehiculoMI);

        jMenuBar3.add(jMenu11);

        jMenu14.setText("Ventas");

        nuevaVentaMI.setText("Nueva Venta");
        nuevaVentaMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nuevaVentaMIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nuevaVentaMIMouseExited(evt);
            }
        });
        nuevaVentaMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVentaMIActionPerformed(evt);
            }
        });
        jMenu14.add(nuevaVentaMI);

        jMenuBar3.add(jMenu14);

        jMenu16.setText("Perfil");

        cambiarContrasenaMI.setText("Cambiar Contraseña");
        cambiarContrasenaMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cambiarContrasenaMIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cambiarContrasenaMIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cambiarContrasenaMIMousePressed(evt);
            }
        });
        cambiarContrasenaMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarContrasenaMIActionPerformed(evt);
            }
        });
        jMenu16.add(cambiarContrasenaMI);

        alta_bajaMI.setText("Alta/Baja De Empleados");
        alta_bajaMI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alta_bajaMIMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alta_bajaMIMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                alta_bajaMIMousePressed(evt);
            }
        });
        alta_bajaMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alta_bajaMIActionPerformed(evt);
            }
        });
        jMenu16.add(alta_bajaMI);

        jMenuBar3.add(jMenu16);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarDatosMIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarDatosMIMousePressed
     
    }//GEN-LAST:event_guardarDatosMIMousePressed

    private void nuevoVehiculoMIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoVehiculoMIMouseEntered
// TODO add your handling code here:
        pieVentanaLB.setText(" Incluir un nuevo vehiculo a la exposicion");
    }//GEN-LAST:event_nuevoVehiculoMIMouseEntered

    private void nuevoVehiculoMIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoVehiculoMIMouseExited
// TODO add your handling code here:
        pieVentanaLB.setText("");
    }//GEN-LAST:event_nuevoVehiculoMIMouseExited

    private void nuevoVehiculoMIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevoVehiculoMIMousePressed
// TODO add your handling code here:
        
    }//GEN-LAST:event_nuevoVehiculoMIMousePressed

    private void nuevaReparacionMIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaReparacionMIMouseEntered
// TODO add your handling code here:
        pieVentanaLB.setText(" Incluir una nueva reparacion");
    }//GEN-LAST:event_nuevaReparacionMIMouseEntered

    private void nuevaReparacionMIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaReparacionMIMousePressed
// TODO add your handling code here:

    }//GEN-LAST:event_nuevaReparacionMIMousePressed

    private void historialVehiculoMIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialVehiculoMIMouseEntered
// TODO add your handling code here:
        pieVentanaLB.setText(" Ver el historial completo de un vehiculo");
    }//GEN-LAST:event_historialVehiculoMIMouseEntered

    private void historialVehiculoMIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialVehiculoMIMouseExited
// TODO add your handling code here:
        pieVentanaLB.setText("");
    }//GEN-LAST:event_historialVehiculoMIMouseExited

    private void historialVehiculoMIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialVehiculoMIMousePressed

    }//GEN-LAST:event_historialVehiculoMIMousePressed

    private void jMenu11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu11MouseExited
// TODO add your handling code here:
        pieVentanaLB.setText("");
    }//GEN-LAST:event_jMenu11MouseExited

    private void nuevaVentaMIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaVentaMIMouseEntered
// TODO add your handling code here:
        pieVentanaLB.setText(" Realizar una nueva Venta");
    }//GEN-LAST:event_nuevaVentaMIMouseEntered

    private void nuevaVentaMIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevaVentaMIMouseExited
// TODO add your handling code here:
        pieVentanaLB.setText("");
    }//GEN-LAST:event_nuevaVentaMIMouseExited

    private void nuevaVentaMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaVentaMIActionPerformed
        
        this.setVisible(false);
        new VentanaVenta(parent, true);
        this.setVisible(true);
        
    }//GEN-LAST:event_nuevaVentaMIActionPerformed

    private void cambiarContrasenaMIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContrasenaMIMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarContrasenaMIMouseEntered

    private void cambiarContrasenaMIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContrasenaMIMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarContrasenaMIMouseExited

    private void cambiarContrasenaMIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cambiarContrasenaMIMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cambiarContrasenaMIMousePressed

    private void cambiarContrasenaMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarContrasenaMIActionPerformed
        
        String nuevaContrasena = JOptionPane.showInputDialog(parent, "Introduce tu nueva contraseña", "Cambiar contraseña", JOptionPane.QUESTION_MESSAGE);
        try {
            System.out.println(codigoUsuario);
            gestorUsuarios.cambiarContrasena(codigoUsuario, nuevaContrasena);
            
        } catch (UsuarioIncorrecto ex) {
            JOptionPane.showMessageDialog(parent, "Error al cambiar la contraseña.", "Nueva contraseña", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_cambiarContrasenaMIActionPerformed

    private void alta_bajaMIMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alta_bajaMIMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_alta_bajaMIMouseEntered

    private void alta_bajaMIMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alta_bajaMIMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_alta_bajaMIMouseExited

    private void alta_bajaMIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alta_bajaMIMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_alta_bajaMIMousePressed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    
        //Solo deberia guardar los cambios si se pulsa en el menu de guardar datos no?
        
        /*try {
            gestorUsuarios.guardarGestorUsuarios();
            concesionario.guardarConcesionario();
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se a podido guardar los datos","fallo",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se a podido guardar los datos","fallo",JOptionPane.ERROR_MESSAGE);
        }*/
        
    }//GEN-LAST:event_formWindowClosed

    private void nuevoVehiculoMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoVehiculoMIActionPerformed
        
        this.setVisible(false);
        new VentanaAdmision(parent, true);
        this.setVisible(true);
        
    }//GEN-LAST:event_nuevoVehiculoMIActionPerformed

    private void alta_bajaMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alta_bajaMIActionPerformed
        
        this.setVisible(false);
        new VentanaAltaBajaUsuarios(parent, true);
        this.setVisible(true);
        
    }//GEN-LAST:event_alta_bajaMIActionPerformed

    private void historialVehiculoMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialVehiculoMIActionPerformed
         
        
        String matricula = JOptionPane.showInputDialog(this, "Introduzca la matricula:", "Ver historial", JOptionPane.QUESTION_MESSAGE);
        
        if(!concesionario.comprobarVenta(matricula))
            JOptionPane.showMessageDialog(this, "El vehiculo buscado no existe", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            this.setVisible(false);
            new VentanaHistorial(parent, true, matricula);
            this.setVisible(true);
        }
       
    }//GEN-LAST:event_historialVehiculoMIActionPerformed

    private void nuevaReparacionMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaReparacionMIActionPerformed
        
        String matricula = JOptionPane.showInputDialog(this, "Introduzca la matricula:", "Iniciar revision", JOptionPane.QUESTION_MESSAGE);
        
        if(!concesionario.comprobarVenta(matricula))
            JOptionPane.showMessageDialog(this, "El vehiculo buscado no existe", "Error", JOptionPane.ERROR_MESSAGE);
        else{
            this.setVisible(false);
            new VentanaReparacion(parent, true, matricula);
            this.setVisible(true);
        }
        
    }//GEN-LAST:event_nuevaReparacionMIActionPerformed

    private void guardarDatosMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDatosMIActionPerformed
        try {
            gestorUsuarios.guardarGestorUsuarios();
            concesionario.guardarConcesionario();
            JOptionPane.showMessageDialog(this, "Guardado completado con exito.", "Guardar cambios.", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Error al guardar los datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_guardarDatosMIActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alta_bajaMI;
    private javax.swing.JMenuItem cambiarContrasenaMI;
    private javax.swing.JLabel fechaLB;
    private javax.swing.JMenuItem guardarDatosMI;
    private javax.swing.JMenuItem historialVehiculoMI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel nombreConcesionarioLB;
    private javax.swing.JMenuItem nuevaReparacionMI;
    private javax.swing.JMenuItem nuevaVentaMI;
    private javax.swing.JMenuItem nuevoVehiculoMI;
    private javax.swing.JLabel pieVentanaLB;
    // End of variables declaration//GEN-END:variables
}
