/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.FechaInvalida;
import Excepciones.FormatoInvalido;
import concesionario.*;
import java.awt.Image;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;



public class VentanaReparacion extends javax.swing.JDialog {

    private JFrame parent;
    private String matricula;
    private Concesionario concesionario;
    
    public VentanaReparacion(JFrame parent, boolean modal, String matricula) {
        super(parent, modal);
        this.matricula = matricula;
        this.parent=parent;
        concesionario = Concesionario.getInstance();
        initComponents();
        
        Image imagen = concesionario.getVehiculoVendido(matricula).getVehiculo().getFoto().getImage().getScaledInstance(Utilidades.ANCHO_FOTO, Utilidades.ALTO_FOTO, Image.SCALE_AREA_AVERAGING);
        fotoLB.setIcon(new ImageIcon(imagen));
        cargarDatos();
        this.setTitle("Concesionario X  -> Nueva Reparacion de: " + matricula);
        nombreConcesionarioLB.setText(Utilidades.getNombreConcesionario());
        this.fechaLB.setText(Utilidades.getFechaHoy());
        this.setVisible(true);
        
    }

    
    private void cargarDatos(){
        
        VehiculoVendido vv = concesionario.getVehiculoVendido(matricula);
        Vehiculo v = vv.getVehiculo();
        matriculaLB.setText("Matricula: "+vv.getMatricula());
        dniCifLB.setText("Dni/Cif: "+vv.getDnicif().toString());
        marcaLB.setText("Marca: "+v.getMarca());
        modeloLB.setText("Modelo: "+v.getModelo());
        colorLB.setText("Color: "+v.getColor());
        fechaVVLB.setText("Fecha: "+v.getFecha());
        precioLB.setText("Precio: "+v.getPrecio());
        intervaloLB.setText("Intervalo: "+v.getIntervalo_revisiones());
        campo1LB.setText("Observaciones: "+v.getObservaciones());
        kmLB.setText("Km:"+v.getKilometros());
        
        
        if(v instanceof Camion){
            Camion c = (Camion)v;
            campo1LB.setText("Carga Max: "+c.getCargaMaxima());
            campo2LB.setText("Tara: "+c.getTara());
            //campo3LB.setText("Nº ruedas: "+c.getNumRuedas());
        }
        else if(v instanceof Furgoneta){
            Furgoneta f = (Furgoneta)v;
            campo1LB.setText("Volumen de carga: "+f.getVolumenCarga());
            campo2LB.setText("Longitud de carga: "+f.getLongitudCarga());
            //campo3LB.setText("");
        }
        else if(v instanceof Autobus){
            Autobus a = (Autobus)v;
            campo1LB.setText("Nº pasajeros: "+a.getNumPasajeros());
            campo2LB.setText("Nº ruedas: "+a.getNumRuedas());
            //campo3LB.setText("Video disponible: "+ (a.isVideoDisponible()? "Si" : "No"));
        }
            
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombreConcesionarioLB = new javax.swing.JLabel();
        fechaLB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fechaTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kilometrosTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        actuacionTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precioTF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        aceptarJB = new javax.swing.JButton();
        cancelarJB = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        matriculaLB = new javax.swing.JLabel();
        dniCifLB = new javax.swing.JLabel();
        marcaLB = new javax.swing.JLabel();
        modeloLB = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        colorLB = new javax.swing.JLabel();
        fechaVVLB = new javax.swing.JLabel();
        intervaloLB = new javax.swing.JLabel();
        precioLB = new javax.swing.JLabel();
        kmLB = new javax.swing.JLabel();
        campo1LB = new javax.swing.JLabel();
        campo2LB = new javax.swing.JLabel();
        obeservacionesJB = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        fotoLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        nombreConcesionarioLB.setText("Concesionario X");
        jPanel1.add(nombreConcesionarioLB);

        fechaLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fechaLB.setText("FECHA");
        jPanel1.add(fechaLB);

        getContentPane().add(jPanel1);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AÑADIR UNA NUEVA REPARACION");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos para la reparacion"));
        jPanel3.setLayout(new java.awt.GridLayout(4, 2, 10, 20));

        jLabel4.setText("Fecha de revision (aa/bb/cccc)");
        jPanel3.add(jLabel4);
        jPanel3.add(fechaTF);

        jLabel5.setText("Kilometros");
        jPanel3.add(jLabel5);
        jPanel3.add(kilometrosTF);

        jLabel7.setText("Actuacion");
        jPanel3.add(jLabel7);
        jPanel3.add(actuacionTF);

        jLabel6.setText("Precio");
        jPanel3.add(jLabel6);
        jPanel3.add(precioTF);

        aceptarJB.setText("Aceptar");
        aceptarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarJBActionPerformed(evt);
            }
        });
        jPanel5.add(aceptarJB);

        cancelarJB.setText("Cancelar");
        cancelarJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJBActionPerformed(evt);
            }
        });
        jPanel5.add(cancelarJB);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales del Vehiculo"));
        jPanel4.setLayout(new java.awt.GridLayout(7, 2, 5, 5));
        jPanel4.add(matriculaLB);
        jPanel4.add(dniCifLB);
        jPanel4.add(marcaLB);
        jPanel4.add(modeloLB);
        jPanel4.add(jLabel12);
        jPanel4.add(jLabel13);
        jPanel4.add(colorLB);
        jPanel4.add(fechaVVLB);
        jPanel4.add(intervaloLB);
        jPanel4.add(precioLB);
        jPanel4.add(kmLB);
        jPanel4.add(campo1LB);
        jPanel4.add(campo2LB);

        obeservacionesJB.setText("ver observaciones");
        obeservacionesJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obeservacionesJBActionPerformed(evt);
            }
        });
        jPanel4.add(obeservacionesJB);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen del vehiculo"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(fotoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarJBActionPerformed


        try {
            Utilidades.validarFecha(fechaTF.getText());
            String fecha = fechaTF.getText();
            int km = Integer.parseInt(kilometrosTF.getText());
            String actuacion = actuacionTF.getText();
            double precio = Double.parseDouble(precioTF.getText());
            concesionario.revisionDeMantenimiento(matricula, fecha, km, actuacion, precio);
            this.setVisible(false);
            this.dispose();
        } catch (FechaInvalida e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (FormatoInvalido e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Uno o mas campos no validos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_aceptarJBActionPerformed

    private void cancelarJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJBActionPerformed
// TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelarJBActionPerformed

    private void obeservacionesJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obeservacionesJBActionPerformed

        JOptionPane.showMessageDialog(this, concesionario.getVehiculoVendido(matricula).getVehiculo().getObservaciones(), "Observaciones", JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_obeservacionesJBActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarJB;
    private javax.swing.JTextField actuacionTF;
    private javax.swing.JLabel campo1LB;
    private javax.swing.JLabel campo2LB;
    private javax.swing.JButton cancelarJB;
    private javax.swing.JLabel colorLB;
    private javax.swing.JLabel dniCifLB;
    private javax.swing.JLabel fechaLB;
    private javax.swing.JTextField fechaTF;
    private javax.swing.JLabel fechaVVLB;
    private javax.swing.JLabel fotoLB;
    private javax.swing.JLabel intervaloLB;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField kilometrosTF;
    private javax.swing.JLabel kmLB;
    private javax.swing.JLabel marcaLB;
    private javax.swing.JLabel matriculaLB;
    private javax.swing.JLabel modeloLB;
    private javax.swing.JLabel nombreConcesionarioLB;
    private javax.swing.JButton obeservacionesJB;
    private javax.swing.JLabel precioLB;
    private javax.swing.JTextField precioTF;
    // End of variables declaration//GEN-END:variables
}
