/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.NoTieneRevisiones;
import concesionario.*;
import java.awt.Image;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class VentanaHistorial extends javax.swing.JDialog {

    
    private JFrame parent;
    private String matricula;
    private Concesionario concesionario;
    private ArrayList<Revision> historialRevisiones;
    private int indice;
    
    public VentanaHistorial(JFrame parent, boolean modal, String matricula) {
        super(parent, modal);
        concesionario = Concesionario.getInstance();
        this.matricula = matricula;
        try {
            historialRevisiones = concesionario.getHistorialAL(matricula);
        } catch (NoTieneRevisiones ex) {
            
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            this.setVisible(false);
            this.dispose();
            return;
        }
        initComponents();
        
        Image imagen = concesionario.getVehiculoVendido(matricula).getVehiculo().getFoto().getImage().getScaledInstance(Utilidades.ANCHO_FOTO, Utilidades.ALTO_FOTO, Image.SCALE_AREA_AVERAGING);
        fotoLB.setIcon(new ImageIcon(imagen));
        cargarDatos();
        indice = 0;
        mostrarRevision();
        
        nombreConcesionarioLB.setText(Utilidades.getNombreConcesionario());
        fechaLB.setText(Utilidades.getFechaHoy());
        this.setTitle("Concesionario X  -> Ver Historial de: " + matricula);
        this.setVisible(true);
    }
    
    private void cargarDatos(){
        
        VehiculoVendido vv = concesionario.getVehiculoVendido(matricula);
        Vehiculo v = vv.getVehiculo();
        matriculaLB.setText("Matricula: "+vv.getMatricula());
        dniCifLB.setText("Dni/Cif: "+vv.getDnicif().toString());
        marcaLB.setText("Marca: "+v.getMarca());
        modeloLB.setText("Modelo: "+v.getModelo());
        colorLB.setText("Color: "+v.getColor());
        fechaVVLB.setText("Fecha: "+v.getFecha());
        precioLB.setText("Precio: "+v.getPrecio());
        intervaloLB.setText("Intervalo: "+v.getIntervalo_revisiones());
        campo1LB.setText("Obsers: "+v.getObservaciones());
        kmLB.setText("KM: "+v.getKilometros());
        
        
        if(v instanceof Camion){
            Camion c = (Camion)v;
            campo1LB.setText("Carga Max: "+c.getCargaMaxima());
            campo2LB.setText("Tara: "+c.getTara());
            campo3LB.setText("Nº ruedas: "+c.getNumRuedas());
        }
        else if(v instanceof Furgoneta){
            Furgoneta f = (Furgoneta)v;
            campo1LB.setText("Volumen de carga: "+f.getVolumenCarga());
            campo2LB.setText("Longitud de carga: "+f.getLongitudCarga());
            campo3LB.setText("");
        }
        else if(v instanceof Autobus){
            Autobus a = (Autobus)v;
            campo1LB.setText("Nº pasajeros: "+a.getNumPasajeros());
            campo2LB.setText("Nº ruedas: "+a.getNumRuedas());
            campo3LB.setText("Video disponible: "+ (a.isVideoDisponible()? "Si" : "No"));
        }
            
        
    }
    
    private void mostrarRevision(){
        
        Revision rep = historialRevisiones.get(indice);
        Fecha.setText("Fecha: "+rep.getFecha());
        Kilometros.setText("KM: "+rep.getKilometros());
        Actuacion.setText("Actuacion: "+rep.getActuacion());
        Precio.setText("Precio: "+rep.getPrecio()+" €");
        Anterior.setEnabled(true);
        Siguiente.setEnabled(true);
        
        if (indice==0)
            Anterior.setEnabled(false);
        if (indice==historialRevisiones.size()-1)
            Siguiente.setEnabled(false);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Anterior = new javax.swing.JButton();
        imprimir_historial = new javax.swing.JButton();
        Siguiente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Kilometros = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Actuacion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        matriculaLB = new javax.swing.JLabel();
        dniCifLB = new javax.swing.JLabel();
        marcaLB = new javax.swing.JLabel();
        modeloLB = new javax.swing.JLabel();
        colorLB = new javax.swing.JLabel();
        fechaVVLB = new javax.swing.JLabel();
        intervaloLB = new javax.swing.JLabel();
        precioLB = new javax.swing.JLabel();
        kmLB = new javax.swing.JLabel();
        campo1LB = new javax.swing.JLabel();
        campo2LB = new javax.swing.JLabel();
        campo3LB = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        fotoLB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nombreConcesionarioLB = new javax.swing.JLabel();
        fechaLB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Anterior.setText("Anterior");
        Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnteriorActionPerformed(evt);
            }
        });
        jPanel3.add(Anterior);

        imprimir_historial.setText("Imprimir Historial");
        imprimir_historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimir_historialActionPerformed(evt);
            }
        });
        jPanel3.add(imprimir_historial);

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        jPanel3.add(Siguiente);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la reparacion"));
        jPanel5.setLayout(new java.awt.GridLayout(4, 2));

        jLabel4.setText("Fecha de revision");
        jPanel5.add(jLabel4);
        jPanel5.add(Fecha);

        jLabel5.setText("Kilometros");
        jPanel5.add(jLabel5);
        jPanel5.add(Kilometros);

        jLabel7.setText("Actuacion");
        jPanel5.add(jLabel7);
        jPanel5.add(Actuacion);

        jLabel6.setText("Precio");
        jPanel5.add(jLabel6);
        jPanel5.add(Precio);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIAL DE REPARACION DEL VEHICULO ");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales del Vehiculo"));
        jPanel4.setLayout(new java.awt.GridLayout(6, 2, 10, 10));
        jPanel4.add(matriculaLB);
        jPanel4.add(dniCifLB);
        jPanel4.add(marcaLB);
        jPanel4.add(modeloLB);
        jPanel4.add(colorLB);
        jPanel4.add(fechaVVLB);
        jPanel4.add(intervaloLB);
        jPanel4.add(precioLB);
        jPanel4.add(kmLB);
        jPanel4.add(campo1LB);
        jPanel4.add(campo2LB);
        jPanel4.add(campo3LB);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen del vehiculo"));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(fotoLB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoLB, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        nombreConcesionarioLB.setText("Concesionario X");
        jPanel2.add(nombreConcesionarioLB);

        fechaLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fechaLB.setText("FECHA");
        jPanel2.add(fechaLB);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnteriorActionPerformed

        indice--;
        mostrarRevision();
        
    }//GEN-LAST:event_AnteriorActionPerformed

    private void imprimir_historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimir_historialActionPerformed

        
        try {
            PrintWriter salida = new PrintWriter(new BufferedWriter(new FileWriter(matricula + ".txt")));
            salida.println("    HISTORIAL DE REPARACION DEL VEHICULO CON MATRICULA: " + matricula);
            salida.println();
            salida.println();
            salida.println("Datos generales");
            salida.println();
            

            VehiculoVendido vv = concesionario.getVehiculoVendido(matricula);
            Vehiculo v = vv.getVehiculo();
            salida.println("Propietario: "+vv.getDnicif().toString());
            salida.println("Marca: "+v.getMarca());
            salida.println("Modelo: "+v.getModelo());
            salida.println("Color: "+v.getColor());
            salida.println("Fecha: "+v.getFecha());
            salida.println("Precio: "+v.getPrecio());
            salida.println("Intervalo: "+v.getIntervalo_revisiones());
            salida.println("Observaciones: "+v.getObservaciones());
            salida.println("Kilometros: "+v.getKilometros());


            if(v instanceof Camion){
                Camion c = (Camion)v;
                salida.println("Carga Max: "+c.getCargaMaxima());
                salida.println("Tara: "+c.getTara());
                salida.println("Nº ruedas: "+c.getNumRuedas());
            }
            else if(v instanceof Furgoneta){
                Furgoneta f = (Furgoneta)v;
                salida.println("Volumen de carga: "+f.getVolumenCarga());
                salida.println("Longitud de carga: "+f.getLongitudCarga());
            }
            else if(v instanceof Autobus){
                Autobus a = (Autobus)v;
                salida.println("Nº pasajeros: "+a.getNumPasajeros());
                salida.println("Nº ruedas: "+a.getNumRuedas());
                salida.println("Video disponible: "+ (a.isVideoDisponible()? "Si" : "No"));
            }
            
            salida.println("---------------------------------------------------");
            
            int i = 0;
            for(Revision rep : historialRevisiones){
                salida.println("Reparacion numero: " + (i+1));
                salida.println();
                salida.println("\tFecha de la reparacion: " + rep.getFecha());
                salida.println("\tkilometro: " + rep.getKilometros());
                salida.println("\tActuacion: " + rep.getActuacion());
                salida.println("\tPrecio de la reparacion: " + rep.getPrecio());
                salida.println("---------------------------------------------------");
                i++;
            }


            //Cerramos el stream

            salida.close();
            JOptionPane.showMessageDialog(this, "Se ha completado correctamente la impresion del historial", matricula, JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ioe) {

            JOptionPane.showMessageDialog(this, "Error al imprimir el historial", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_imprimir_historialActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed

        indice++;
        mostrarRevision();
        
    }//GEN-LAST:event_SiguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Actuacion;
    private javax.swing.JButton Anterior;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Kilometros;
    private javax.swing.JLabel Precio;
    private javax.swing.JButton Siguiente;
    private javax.swing.JLabel campo1LB;
    private javax.swing.JLabel campo2LB;
    private javax.swing.JLabel campo3LB;
    private javax.swing.JLabel colorLB;
    private javax.swing.JLabel dniCifLB;
    private javax.swing.JLabel fechaLB;
    private javax.swing.JLabel fechaVVLB;
    private javax.swing.JLabel fotoLB;
    private javax.swing.JButton imprimir_historial;
    private javax.swing.JLabel intervaloLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel kmLB;
    private javax.swing.JLabel marcaLB;
    private javax.swing.JLabel matriculaLB;
    private javax.swing.JLabel modeloLB;
    private javax.swing.JLabel nombreConcesionarioLB;
    private javax.swing.JLabel precioLB;
    // End of variables declaration//GEN-END:variables
}
