/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Excepciones.UsuarioIncorrecto;
import concesionario.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;



public class VentanaUsuariosFotos extends javax.swing.JFrame {

    private GestorUsuarios gestorUsuarios;
    private final int ALTO_FOTO = 150;
    private final int ANCHO_FOTO = 160;
    private String codigoUsuario;
    private JFrame F;

    public VentanaUsuariosFotos() {

        initComponents();
        F = this;
        this.setResizable(false);        
        panelFotosJP.setLayout(new ModifiedFlowLayout(FlowLayout.LEFT));
        gestorUsuarios = GestorUsuarios.getInstance();
        try {
            gestorUsuarios.cargarGestorUsuarios();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "No se a podido cargar los datos","fallo",JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "No se a podido cargar los datos","fallo",JOptionPane.ERROR_MESSAGE);
        }
        pintarFotos();
        
        nombreConcesionarioLB.setText(Utilidades.getNombreConcesionario());
        fechaLB.setText(Utilidades.getFechaHoy());
        this.setVisible(true);
    }
    
    private void pintarFotos(){
        
        panelFotosJP.removeAll();
        
        Iterator<String> it = gestorUsuarios.getIteradorClaves();
        JButton buttonFoto;
        Usuario user;
        Image imagen;
        
        try {
            while (it.hasNext()) {
                user = gestorUsuarios.obtenerUsuario(it.next());
                if (user.getFoto() != null) {
                    imagen = user.getFoto().getImage().getScaledInstance(ANCHO_FOTO, ALTO_FOTO, Image.SCALE_AREA_AVERAGING);
                    buttonFoto = new JButton();
                    buttonFoto.setIcon(new ImageIcon(imagen));                    
                    buttonFoto.setToolTipText(user.getCodigo());
                    buttonFoto.setBackground(Color.WHITE);
                    buttonFoto.addActionListener(new ActionListener() {

                        public void actionPerformed(ActionEvent e) {
                            JButton boton = (JButton) e.getSource();
                            codigoUsuario = boton.getToolTipText();
                            F.setVisible(false);
                            new VentanaValidacionUsuario(F, true, codigoUsuario);
                            pintarFotos();
                            F.setVisible(true);
                        }
                    });
                
                    panelFotosJP.add(buttonFoto);
                }
            }
        } catch (UsuarioIncorrecto ui) {
            //
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreConcesionarioLB = new javax.swing.JLabel();
        fechaLB = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelFotosJP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bienvenido al "+ Utilidades.getNombreConcesionario());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Listado de usuarios:");

        nombreConcesionarioLB.setText("Concesionario X");

        fechaLB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        fechaLB.setText("FECHA");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelFotosJP.setAutoscrolls(true);

        javax.swing.GroupLayout panelFotosJPLayout = new javax.swing.GroupLayout(panelFotosJP);
        panelFotosJP.setLayout(panelFotosJPLayout);
        panelFotosJPLayout.setHorizontalGroup(
            panelFotosJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        panelFotosJPLayout.setVerticalGroup(
            panelFotosJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelFotosJP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreConcesionarioLB, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fechaLB, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreConcesionarioLB)
                    .addComponent(fechaLB))
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fechaLB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombreConcesionarioLB;
    private javax.swing.JPanel panelFotosJP;
    // End of variables declaration//GEN-END:variables
}
